### ISSUE TITLE
Edit thresholds

### ISSUE THREAD

**Issue by skazn** [csci427/canary#11]
@AaronStGeorge

**Comment by AaronStGeorge** [comment]
Want to flesh this one out a little more?

**Comment by skazn** [comment]
@AaronStGeorge The user can't edit their thresholds at all after they are set. What if they make a mistake? Also can you add the high and low thresholds to the monitor fragment so they display?

**Comment by AaronStGeorge** [comment]
@skazn I see what you mean. Everything is set up so if you relaunch the fragment it should edit the threshold without any errors. Maybe a long click could re-open the fragment?

**Comment by AaronStGeorge** [comment]
@skazn I can work on the high and low thresholds on the monitor fragment. The main page stuff was sort of yours now, do you want to get a long click or similar to re-open the threshold?

**Comment by rlank** [comment]
@AaronStGeorge @skazn I have longClick bound for deletion of fragments. We could piggyback and give them an option (edit or delete) but wait till I push changes to viewmanager (where the clicklisteners are now)
