### ISSUE TITLE
Thresholds allow for high-low crossover

### ISSUE THREAD

**Issue by skazn** [csci427/canary#12]
@AaronStGeorge 

ex. you can set the high threshold at something low like 10 and the low threshold at a higher bound than what you set the high threshold, like 15

**Comment by AaronStGeorge** [comment]
I was aware of this but didn't really know what to do about it. Maybe the "set threshold's" button could be greyed out when threshold crossover. I'll look into this to see if it's possible.

**Comment by skazn** [comment]
Well it will be confusing if they cannot for some reason press the button. What if we do a logic check when they hit the button and if its wrong can we give them a Toast message and then just keep the popup open.

**Comment by AaronStGeorge** [comment]
Alright, I like that idea
