### ISSUE TITLE
abstract factory no longer working.

### ISSUE THREAD

**Issue by skazn** [csci427/canary#14]
@AaronStGeorge so I'm not certain what you did you change the noninvasive blood pressure thing but it is not working now. Also the label didn't change.

Can you fix it?

**Comment by AaronStGeorge** [comment]
@skazn yeah I changed that name, but didn't change it in the other places it needed to be changed. I've fixed it in my code. Working on #13 right now, when I push that stuff this should be fixed.

**Comment by skazn** [comment]
@AaronStGeorge Thanks Man!
