### ISSUE TITLE
Adding second monitor crashes app

### ISSUE THREAD

**Issue by AaronStGeorge** [csci427/canary#4]
This bug does't have anything to do with the Audio/Alert service. With the entire audio/alert service removed, this bug persists.

**Comment by rlank** [comment]
Do you mean adding the first monitor, or adding a second or more monitors?

**Comment by AaronStGeorge** [comment]
The second, sorry I wasn't clear

**Comment by skazn** [comment]
@AaronStGeorge @rlank We can leave this open for now. We have a fall back on forcing portrait mode. If we decide to go that route it closes basically all of these bugs

**Comment by AaronStGeorge** [comment]
Forcing portrate mode fixes this bug
